### ISSUE TITLE
Doesn't work on W7

### ISSUE THREAD

**Issue by odnarb** [bcherny/node-timezone#1]
Tried different approaches. Worked on my Ubuntu 16.04 VM.

node-timezone@0.0.3
npm v3.10.3
node.js v6.5.0

> var getTimezone = require('node-timezone').getTimezone
undefined
> console.log(getTimezone())
Error: Command failed: date +%Z
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at module.exports.getTimezone (C:\Users\xxxxxxx\Desktop\node_modules\node-timezone\index.js:16:56)
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
> console.log(getTimezone());
Error: Command failed: date +%Z
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at module.exports.getTimezone (C:\Users\xxxxxxx\Desktop\node_modules\node-timezone\index.js:16:56)
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
> var getTimezone = require('node-timezone').getTimezone
undefined
> getTimezone()
Error: Command failed: date +%Z
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at module.exports.getTimezone (C:\Users\xxxxxxx\Desktop\node_modules\node-timezone\index.js:16:56)
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
>
(To exit, press ^C again or type .exit)

**Comment by odnarb** [comment]
Sorry just realized you didn't have a binary pointed to for windows env's.. yea windows sucks when it comes to this kind of support.

```sh
  var tz = execSync('date +%Z', { encoding: 'utf-8' }).trim()
```

The best option for some windows env's might be:

```sh
wmic timezone get StandardName
```

**Comment by bcherny** [comment]
@odnarb Is the issue that it doesn't work with Node 7, or doesn't work on Windows?

**Comment by bcherny** [comment]
I see, you meant Windows 7. See [note in the README](https://github.com/bcherny/node-timezone#tests):

> Tested on OSX and Ubuntu. TODO: Test on Windows.

PRs are appreciated!
